version: '3'

services:
  django:
    build: .
    container_name: django 
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
  
  db:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - .:/code
